using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class katana : MonoBehaviour
{
    public GameObject brokenBoxPrefab; // Prefab de la caja por partes
    public GameObject box;
    
    public Collider specifiedCollider;
    private void OnCollisionEnter(Collision collision)
    {
        if (collision.collider.CompareTag("Box") && collision.collider == specifiedCollider) // Comprueba si la colisi贸n es con la caja
        {
            BreakBox(); // Llama a la funci贸n para romper la caja
        }
    }

    private void BreakBox()
    {
        // Instancia el prefab de la caja por partes en la misma posici贸n y rotaci贸n
        Instantiate(brokenBoxPrefab, box.transform.position, box.transform.rotation);

        // Destruye la caja normal
        Destroy(box);
    }
}
